source = $HOME/.config/hypr/nord.conf

$accent = $nord9
$accentAlpha = $nord9Alpha
$font = Maple Mono

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Downloads/nord_alone_tree.png
  blur_passes = 1
  color = $nord1
}


# TIME
label {
  monitor =
  text = $TIME
  color = $nord5
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $nord5
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT";
  color = "$text";
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# USER AVATAR
image {
  monitor =
  path = ~/Downloads/gears(1).png
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $nord3
  font_color = $nord4
  fade_on_empty = false
  placeholder_text = <i>󰌾   Locked   󰌾</i>
  hide_input = false
  check_color = $accent
  fail_color = $nord11
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $nord13
  position = 0, -47
  halign = center
  valign = center
}
