$nord0=  rgb(2e3440)
$nord0Alpha=  2e3440

$nord1=  rgb(3b4252)
$nord1Alpha=  3b4252

$nord2=  rgb(434c5e)
$nord2Alpha=  434c5e

$nord3=  rgb(4c566a)
$nord3Alpha=  4c566a

$nord4=  rgb(d8dee9)
$nord4Alpha=  d8dee9

$nord5=  rgb(e5e9f0)
$nord5Alpha=  e5e9f0

$nord6=  rgb(eceff4)
$nord6Alpha=  eceff4

$nord7=  rgb(8fbcbb)
$nord7Alpha=  8fbcbb

$nord8=  rgb(88c0d0)
$nord8Alpha=  88c0d0

$nord9=  rgb(81a1c1)
$nord9Alpha=  81a1c1

$nord10= rgb(5e81ac)
$nord10Alpha= 5e81ac

$nord11= rgb(bf616a)
$nord11Alpha= bf616a

$nord12= rgb(d08770)
$nord12Alpha= d08770

$nord13= rgb(ebcb8b)
$nord13Alpha= ebcb8b

$nord14= rgb(a3be8c)
$nord14Alpha= a3be8c

$nord15= rgb(b48ead)
$nord15Alpha= b48ead
